# Generated by Django 5.2.10 on 2026-01-28 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0234a_fork_space_default_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='diameter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recipe',
            name='diameter_text',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
